### ISSUE TITLE
Неосмысленное название функции

### ISSUE THREAD

**Issue by ilya-grigoriev** [Cjkjvfnby/run_only_needed_actions#1]
- Есть следующая функция:
```python
def read(path: Path = Path(__file__).parent / "config.toml") -> FileChecker:
```
- Исходя ТОЛЬКО из названия функции, я не понимаю, что именно она читает.
- Да, если посмотреть в docstring, то все станет понятно. Но не лучше ли назвать функцию, например `read_file`?

**Comment by Cjkjvfnby** [comment]
Спасибо за комментарий, код еще в сыром виде, но приходится его заливать на ГитХаб для тестирования.  Перед публикацией его буду причёсывать.
